#!/bin/bash

set -e
set -x

SCRIPTNAME=$(basename $0)
CLI_ARGS="$@"

function help(){
  cat <<EOF
  $scriptname:
      Convert a coco file to a TfRecord, by converting to intermediate VOC first.
      Currently uses a 75/25 % split between train and val sets.

  usage:
      $scriptname [--check-labels] coco_path image_source_dir

  arguments:
      coco_path: the path to the coco file to convert
      image_source_dir: the path to the directory that contains the images referred to in the coco file

  options:
      --check-labels: Go through each generated VOC label and display the label value counts. This is
                      useful to check if the labels match the class numbers expected

  example:
      $scriptname --check-labels coco_trainvaltest_combined.json images
EOF
}

function info(){
  echo "[$SCRIPTNAME] $@" 1>&2
}

function flag_present(){
  local flag="$1"
  grep -- "$flag" <<<"$CLI_ARGS" 1>/dev/null 2>/dev/null
  return $?
}

if flag_present "--help"; then
  help
  exit 1
fi

if (( $# < 2 )) ; then
  info "Error: coco_path and image_source_dir not given."$"\n"
  help
  exit 1
fi

#LABELSET_DIR=~/src/projects/anadarko/label-sets/example-test
#IMAGE_SOURCE_DIR="/mnt/rhino/processed/industry-data/anadarko/gunnison/r2s/sphericals/CD -/cubes"
COCO_PATH="$1"
LABELSET_DIR=$(dirname $COCO_PATH)
IMAGE_SOURCE_DIR="$2"
 
#Make relevant VOC structures
mkdir "$LABELSET_DIR/voc/JPEGImages" \
      "$LABELSET_DIR/voc/SegmentationClassRaw" \
      "$LABELSET_DIR/voc/ImageSets/Segmentation" \
      "$LABELSET_DIR/tfrecord"
 
cd "$LABELSET_DIR"
 
# First create symlinks to relevant images
jq '.images[].file_name'  "$COCO_PATH" | sed 's/"//g' > "$LABELSET_DIR/images.csv" # Extract image filenames from COCO
cd "$LABELSET_DIR/JPEGImages"
cat "$LABELSET_DIR/images.csv" | while IFS=$"\n" read -r filename; do ln -s "$IMAGE_SOURCE_DIR/$filename"; done
 
#If needed, resize the dataset (e.g. labelbox we use smaller images, need to resize back to (4000, 4000)
cd $LABELSET_DIR
#coco-calc resize --size 4000,4000 <labels.coco.json >labels.big.coco.json
 
# Create the VOC label images
# #TODO: Currently handling images with no annotations very poorly, ensure every image has at least one annotation
coco-to-voc "$COCO_PATH"  SegmentationClassRaw -v -v --image-dir JPEGImages
 
# Check the label images contain the labels you expect
if flag_present "--check-labels"; then
  convert SegmentationClassRaw/*.png -define histogram:unique-colors=true -format "%f %c" histogram:info:- # This will take a while
fi

# List all images (images without anns dropped in coco-to-voc)
ls -1 SegmentationClassRaw/*.png | while IFS=$'\n' read -r filename ; do basename "$filename"; done | sed 's/\.png//' > images.filtered.csv
 
# Create the train and val split (below hardcoded for 75% train, 25% val)
NUM_IMAGES=$(wc -l <images.filtered.csv)
shuf images.filtered.csv | head -n $(( NUM_IMAGES * 3 / 4 )) | sort >ImageSets/Segmentation/train.txt
comm -23 images.filtered.csv ImageSets/Segmentation/train.txt  | sort >ImageSets/Segmentation/val.txt
 
# Run below to check there are no common lines between train and val
if [[ ! -z $(comm -12 ImageSets/Segmentation/*) ]] ; then
    info "Error: COMMON LINES IN TRAIN AND VAL"
fi




### Now run VOC to TfRecord

# Execute from path tensorflow_models/research/deeplab/datasets
DEEPLAB_DIR="~/src/tensorflow_models/research/deeplab/datasets" #TODO: Find a way to include this configurable 


ls -ald $LABELSET_DIR/JPEGImages $LABELSET_DIR/ImageSets/Segmentation $LABELSET_DIR/SegmentationClassRaw $LABELSET_DIR/tfrecord 1>&2
# Check all dirs exist
if $? ; then
  info "iERROR: There is a dir in the VOC structure that does not exist."
  exit 1
fi
 
python3 "$DEEPLAB_DIR/build_voc2012_data.py" \
    --image_folder "$LABELSET_DIR/JPEGImages" \
    --list_folder "$LABELSET_DIR/ImageSets/Segmentation" \
    --semantic_segmentation_folder "$LABELSET_DIR/SegmentationClassRaw" \
    --output_dir "$LABELSET_DIR/tfrecord" \
    --image_format jpg --label_format png
 
#If nothing happens above you have probably forgotten to make train/val .txt files.


