#!/usr/bin/env python3
from argparse import ArgumentParser
import json
import sys
import abyss_deep_learning.draw
import cv2
import errno
import os


DESCRIPTION = \
"""
Draws annotations on images provided from a coco-json file. The json file is taken in from stdin and processed
\n
eg. cat coco-file.json | coco-draw


"""


JSON_SAMPLE = """
{
    "colors":[
        {"name": "PF",  "color":"255,255,0"},
        {"name": "JD",  "color":"0,255,0"},
        {"name": "AA",  "color":"255,0,0"}
    ]
}

"""



def main(command_line_args=None):
    

    if command_line_args.sample_colors:
        print(JSON_SAMPLE)
        return

    coco_file = json.load(sys.stdin)
    category_dict = {}
    default_color_pallette = [
        [255,0,0],
        [0,255,0],
        [255,0,255],
        [255,255,0],
        [0,255,255]*10
    ]


    active_color_pallette = default_color_pallette
    for category in coco_file['categories']:
        category_dict[category['id']] = category['name']



    # Colours loops over the category ids and override the colour pallette for a given category id
    if command_line_args.colors:
        color_json = json.load(open(command_line_args.colors,"r"))
        for ent in color_json['colors']:
            for cat in coco_file['categories']:
                if cat['name'] == ent['name']:
                    ab = ent['color'].split(',')
                    default_color_pallette[cat['id']-1] = [int(ab[0]), int(ab[1]), int(ab[2])]
                    print("using custom color for {}".format(ent['name']))

    for image in coco_file['images']:
        labels = [] # Labels either bbox or segmentation
        text_labels = [] # Text Labels with Text and origin
        cv2_image = cv2.imread(image['path'])
        if cv2_image is None:
            print("coco-draw : error, image not found \"{}\"".format(image['path']), file=sys.stderr)
            continue

        for annotation in coco_file['annotations']:

            if 'score' in annotation:
                annotation_text = "{} -  score: {}".format(category_dict[annotation['category_id']],str(annotation['score']))
            else:
                annotation_text = "{}".format(category_dict[annotation['category_id']])

            if image['id'] == annotation['image_id']:
                if command_line_args.bbox:
                    # convert from x,y,w,h to x1,y1 x2,y2
                    bb_ann = annotation['bbox']
                    labels.append([bb_ann[0], bb_ann[1], bb_ann[0]+bb_ann[2], bb_ann[1]+bb_ann[3], annotation['category_id']-1])
                    text_labels.append([bb_ann[0],bb_ann[1]-8,annotation_text,annotation['category_id']-1])
                else:
                    seg_ann = annotation['segmentation']
                    labels.append([seg_ann[0],annotation['category_id']-1])
                    if len(seg_ann) > 0:
                        text_labels.append([seg_ann[0][0],seg_ann[0][1],annotation_text,annotation['category_id']-1])


        if command_line_args.bbox:
            cv2_image = abyss_deep_learning.draw.boxes(labels,
                                                       cv2_image,
                                                       command_line_args.fill,
                                                       True,
                                                       active_color_pallette,
                                                       command_line_args.annotation_alpha,
                                                       command_line_args.image_alpha,
                                                       command_line_args.border)                                      
        else:
            cv2_image = abyss_deep_learning.draw.polygons(labels,
                                            cv2_image,
                                            command_line_args.fill,
                                            True,
                                            active_color_pallette,
                                            command_line_args.annotation_alpha,
                                            command_line_args.image_alpha,
                                            command_line_args.border)

        cv2_image = abyss_deep_learning.draw.text(text_labels,cv2_image,active_color_pallette,font=cv2.FONT_HERSHEY_SIMPLEX, alpha=1.0, image_alpha=1, scale=command_line_args.text_scale,thickness=1)
        
        
        if command_line_args.view_only:
            cv2.imshow("View Only",cv2_image)
            cv2.waitKey(0)
        else:
            # print("not vo")
            if command_line_args.output:
                try:
                    os.makedirs(command_line_args.output+"/"+os.path.split(image['path'])[0])
                except OSError as err:
                    if err.errno != errno.EEXIST:
                        raise
                
                cv2.imwrite(command_line_args.output+"/"+image['path'],cv2_image)
            else:
                if os.path.isfile(image['path']) and not command_line_args.force:
                    print("coco-draw warning attempting to overwrite images. These images may be potentially your source iamges!!!. Please be careful\napply --froce to override. Exiting.", file=sys.stderr)
                    sys.exit(1)
                else:
                    cv2.imwrite(image['path'],cv2_image)





def parse_cli():
    parser = ArgumentParser(
        description=DESCRIPTION)
    parser.add_argument('-o', '--output', type=str,
                        help="If specified, sets the output directory of the images, otherwise the current directory will be used as the output")
    parser.add_argument('-c', '--colors','--colours', type=str,
                        help="If specified uses json file to determine the colours for each label, otherwise deterministic defaults are used.")
    parser.add_argument('-f', '--force', action='store_true' ,
                        help="Force Overwriting of files when writing to output")
    parser.add_argument('-l', '--fill', action='store_true' ,
                        help="Fills the annotations, if this is not specified only an outline is drawn")
    parser.add_argument('--sample-colors', '--sample-colours', action='store_true' ,
                    help="Prints an example json file to stdout") 
    parser.add_argument('--view-only', '-d', action='store_true' ,
                    help="Only view images, do not write")                      
    parser.add_argument('-b', '--bbox', action='store_true' ,
                        help="If specified, draws only bounding boxes, otherwise will default to segmentation")
    parser.add_argument('-t', '--border', type=int, default=1,
                        help="Specifies border thinkness of annotations")
    parser.add_argument('-u', '--annotation-alpha', type=float,default=0.4,
                        help="Sets the alpha channel of annotations. value is from 0 to 1")
    parser.add_argument('-v', '--image-alpha', type=float, default=1,
                        help="Sets the alpha channel of image. value is from 0 to 1")
    parser.add_argument('-s', '--text-scale', type=float, default=0.4,
                        help="Sets the text scale of annotations")
    return parser.parse_args()

if __name__ == '__main__':
    main(command_line_args=parse_cli())
