#!/usr/bin/python3
"""
This utility is designed to get a COCO database with masks, and output the images with the masks overlayed.
"""

import argparse
import cv2
import os
import json
import pycocotools.mask as pcm
from pycocotools.coco import COCO
import ast
import numpy as np


def get_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawTextHelpFormatter,
        description="""
    This utility is designed to get a COCO database with masks, and output the images with the masks overlayed.
    """
    )
    parser.add_argument("coco", help="Path to the coco database")
    parser.add_argument("output_dir", help="The output directory")
    parser.add_argument("--target_labels", help="A string of the target label e.g. (\"pipe\"), or a list of target labels in str format - for example \"[\"pipe\",\"flange\"]\"")
    parser.add_argument("--background_brightness", type=float, default="1.0", help="The brightness of the background - 1.0=normal, 0.0=black")
    parser.add_argument("--dilation", type=int, default="0", help="Used to expand the mask - this is the size of the kernel")
    parser.add_argument("--output_format", type=str, default=".jpg", help="The output format of the images")
    parser.add_argument("--save_unannotated", type=bool, default=False, help="Save the images that haven't been annotated")
    return parser.parse_args()


def main(args):
    """
    Loads the coco dataset.

    Gets a list of images in the dataset.

    For each image, finds the associated labels.

    From the annotation, applies the mask of the area of interest.

    Saves the image.

    Args:
        args:

    Returns:

    """
    # Make the output directory
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    # Load the dataset
    coco = COCO(args.coco)
    # Get all the image IDs
    imgIds = coco.getImgIds(imgIds=[])
    if args.target_labels:
        if "[" in args.target_labels:
            lit_eval = ast.literal_eval(args.target_labels)
            if isinstance(lit_eval, list):
                target_labels = lit_eval
            else:
                raise ValueError("Target label needs to be either a string or a list - list not interpreted properly")
        else:
            target_labels = [args.target_labels]

        cats = coco.loadCats(coco.getCatIds())

        targetCatIds = []

        # Get the category names
        for cat in cats:
            if cat['name'] in target_labels or cat['name'].lower() in target_labels:
                targetCatIds.append(cat['id'])
    else:
        targetCatIds = None

    # For each image
    for iid in imgIds:
        # Load the image
        img = coco.loadImgs(ids=[iid])[0]
        image = cv2.imread(img['file_name'])
        # Get the annotations for this image
        annIds = coco.getAnnIds(imgIds=[iid])
        # Load the annotation
        anns = coco.loadAnns(annIds)
        # Cycle through each annotation
        mimage = image
        for ann in anns:
            # Test if targetCategory IDs were specified, and if they were, test if the targetCategoryIDs is present for this annotation
            if not targetCatIds or ann['category_id'] in targetCatIds:
                # Retrieve the mask
                mask = pcm.decode(ann['segmentation'])
                # If dilation kernel is greater than 0, dilate the image
                if args.dilation > 0:
                    kernel = np.ones((args.dilation, args.dilation), np.uint8)
                    mask = cv2.dilate(mask,kernel,iterations = 1)
                # If background_brightness is less than 1.0
                if args.background_brightness < 1.0:
                    # Make the foreground
                    fg = cv2.bitwise_and(mimage, mimage, mask=mask)
                    # Make the background mask
                    bgmask = cv2.bitwise_not(255*mask)
                    # Make the background, while adjusting the brightness (making it darker)
                    bg = cv2.bitwise_and(mimage, mimage, mask=bgmask)*args.background_brightness
                    bg = bg.astype(np.uint8)
                    # Add the foreground and background together
                    cv2.add(fg, bg, mimage)
                else:
                    mimage = cv2.bitwise_and(mimage, mimage, mask=mask)

        if args.save_unannotated or len(anns) > 0:
            # Get the filepath
            output_filepath = os.path.join(args.output_dir, os.path.basename(img['file_name']).split('.')[0] + args.output_format)
            if args.output_format == "jpg":
                cv2.imwrite(output_filepath, mimage, [int(cv2.IMWRITE_JPEG_QUALITY), 90])
            else: # TODO for PNG
                cv2.imwrite(output_filepath, mimage)

if __name__ == "__main__":
    main(get_args())
