#!/usr/bin/env python3
import argparse
from keras import backend as K
from keras_retinanet import layers, models
import tensorflow as tf
import os

description = """

Convert Keras (h5) model to TensorFlow Protobuff (pb) model

Usage:
    h5-to-protobuff model.h5 frozen_graph.pb

Use Cases:
    To allow translation of models for use in other utilities that require protobuff format.
    As of writing (10.5.19), Retinanet (Object Detection) uses H5 models whilst DeepLab (Semantic Segmentation)
    uses Protobuff (.pb) models.

"""

def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = tf.graph_util.convert_variables_to_constants(
            session, input_graph_def, output_names, freeze_var_names)
        return frozen_graph


def main(args):

    # Create, compile and train model...

    model = models.load_model(args.h5, backbone_name=args.backbone)

    frozen_graph = freeze_session(K.get_session(),
                                  output_names=[out.op.name for out in model.outputs])


    tf.train.write_graph(frozen_graph, os.path.dirname(args.output), args.output, as_text=False)

def get_args():
    parser = argparse.ArgumentParser(description=description, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('h5', help="h5 file to be converted")
    parser.add_argument('output', help="Output protobuff file")
    parser.add_argument('--backbone',
                            help='The backbone of the Keras H5 model. Default is %(default)s',
                            default='resnet50')
    return parser.parse_args()

if __name__ == '__main__':
    main(get_args())
