#!/bin/bash
#Use this file to pull from a repo that was cloned using a deployment key
REPO="$1"
REMOTE="$2"
BRANCH="$3"
cd "~/src/abyss/$REPO"
GIT_SSH_COMMAND="ssh -i ~/.ssh/git-$REPO -F /dev/null" git pull "$REMOTE" "$BRANCH"
