#!/bin/bash

GIT_URI="$1"
KEY="$2"

# HOME=/home/docker
# touch $HOME/.ssh/config
# mv $HOME/.ssh/config $HOME/.ssh/config.tmp
# cat <<EOF > "$HOME/.ssh/config"
# Host github.com
#   HostName github.com
#   User git
#   IdentityFile $KEY
#   IdentitiesOnly yes
# EOF


# git clone $GIT_URI
# mv $HOME/.ssh/config.tmp $HOME/.ssh/config

#!/bin/bash
#Use this file to pull from a repo that was cloned using a deployment key
GIT_SSH_COMMAND="ssh -i $KEY -F /dev/null" git clone "$GIT_URI"
