#!/usr/bin/python
import os
import json
import pandas as pd
import sys


example = '''

echo '{ "annotations": [ { "id": 0, "image_id": 2, "category_id": 0 }, { "id": 1, "image_id": 3, "category_id": 1 } ], "categories": [ { "id": 0 }, { "id": 1 } ], "images": [ { "id": 2 }, { "id": 3 } ] }' | examples/generic-select  a "a.id == c.id"

'''


what = sys.argv[1]
expr = sys.argv[2]
j = json.loads(sys.stdin.read())
adf = pd.DataFrame(j['annotations'])
cdf = pd.DataFrame(j['categories'])
idf = pd.DataFrame(j['images'])
m = adf.merge(cdf, left_on='category_id', right_on='id').merge(idf, left_on='image_id', right_on='id')
m.columns = ['a.'+c for c in adf.columns] + ['c.'+c for c in cdf.columns] + ['i.'+c for c in idf.columns]
t = ','.join(m.columns)
class D(): pass
code = '\n'.join( [ t + " = r", "result = (" + expr + ")", "if result: print r.values" ] )
compiled = compile(code, '<string>', 'exec')
for i, r in m.iterrows():
    a = D()
    c = D()
    i = D()
    result = False
    exec compiled in {'r': r, 'a': a, 'c': c, 'i': i, 'result': result}
