#!/bin/bash

function usage()
{
    cat <<eof >&2
    
usage: ./realtime-cctv-xception-classification <video>
       cv-cat --file my-video.mp4 | ./realtime-cctv-xception-classification -
       cv-cat --camera | ./realtime-cctv-xception-classification -

original video and inference video will be displayed

square in the upper right corner of inference video will be
white on normal pipeline; the more red it turns, the more
likely there is a fault in the pipeline
    
eof
    exit
}

[[ -n "$1" ]] || usage

frozen_graph="/mnt/pond/processed/abyss-internal/cctv/classification/models/frozen-graph-demo/frozen_graph.pb"
video="$1"

if [[ "$video" == "-" ]]; then cv-cat "resize=320,240;transpose;convert-to=f,0.0078,-1" --output no-header
else cv-cat --file "$video" "view;resize=320,240;transpose;convert-to=f,0.0078,-1" --output no-header; fi \
    | tensor-cat --input input_1:0 --output logits/Softmax:0 --graph "$frozen_graph" --keep-input --verbose \
    | python3 -c "
import numpy as np
import os
import sys

i = np.zeros( ( 320, 240, 3 ), dtype = np.float32 )
s = np.zeros( ( 2 ), dtype = np.float32 )
with os.fdopen( sys.stdout.fileno(), 'wb' ) as stdout:
    with os.fdopen( sys.stdin.fileno(), 'rb' ) as stdin:
        while True:
            if stdin.readinto( i ) != 320 * 240 * 3 * 4: break
            if stdin.readinto( s ) != 2 * 4: break
            i = i.reshape( 320, 240, 3 )
            c = ( ( s[1] - 0.1 ) / 0.9 ) * 2 - 1
            print( s[0], file = sys.stderr )
            d = int( s[1] * 80 ) + 80
            i[269:301,14:46] = [ -1, -1, -1 ]
            i[270:300,15:45] = [ c, c, 1 ]
            i[285,80:160] = [ -1, -1, -1 ]
            i[280:290,d] = [ -1, -1, -1 ]
            stdout.write( i.tobytes() )
            stdout.flush()
" \
    | cv-cat --input "rows=320;cols=240;type=3f;no-header" "transpose;convert-to=f,127,128;convert-to=ub;resize=2;text=fault,530,140,black;text=no fault,500,360,black;view;null"
