#!/bin/bash

cv-cat --camera "resize=906,513;crop=196,0,513,513;timestamp;view" --output no-header \
    | csv-thin 0.1 --deterministic --binary s[$(( 513 * 513 * 3 ))] \
    | tensor-cat --frozen-graph /mnt/pond/processed/industry-data/anadarko/gunnison/segmentation/models/best/frozen_inference_graph.pb \
                 --input ImageTensor:0 \
                 --input-shape 1,513,513,3 \
                 --output SemanticPredictions:0 \
    | cv-cat --input "rows=513;cols=513;type=i;no-header" \
          "brightness=50000;timestamp;view;null"
